"""Data models for OpenDisplay devices."""

from .advertisement import (
    AdvertisementData,
    AdvertisementTracker,
    ButtonChangeEvent,
    ButtonEventData,
    Sht40Reading,
    decode_button_event,
    decode_sht40,
    parse_advertisement,
)
from .buzzer_activate import BuzzerActivateConfig, BuzzerPattern, BuzzerStep, note_to_index
from .capabilities import DeviceCapabilities
from .config import (
    BinaryInputs,
    DataBus,
    DataExtended,
    DisplayConfig,
    FlashConfig,
    GlobalConfig,
    LedConfig,
    ManufacturerData,
    NfcConfig,
    PassiveBuzzer,
    PowerOption,
    SecurityConfig,
    SensorData,
    SystemConfig,
    TouchController,
    WifiConfig,
)
from .config_json import config_from_json, config_to_json
from .enums import (
    ActiveLevel,
    BoardManufacturer,
    BusType,
    DIYBoardType,
    FitMode,
    FlashIcType,
    ICType,
    NfcFieldDetectMode,
    NfcIcType,
    NfcRecordType,
    OpenDisplayBoardType,
    PowerMode,
    RefreshMode,
    Rotation,
    SeeedBoardType,
    SolumBoardType,
    TouchIcType,
    WaveshareBoardType,
    get_board_type_name,
    get_manufacturer_name,
)
from .firmware import FirmwareVersion, firmware_ota_asset, firmware_release_repo
from .led_flash import LedFlashConfig, LedFlashStep

__all__ = [
    "AdvertisementData",
    "AdvertisementTracker",
    "ButtonChangeEvent",
    "ButtonEventData",
    "Sht40Reading",
    "decode_sht40",
    "parse_advertisement",
    "decode_button_event",
    "ActiveLevel",
    "BinaryInputs",
    "BoardManufacturer",
    "BuzzerActivateConfig",
    "BuzzerPattern",
    "BuzzerStep",
    "note_to_index",
    "BusType",
    "DIYBoardType",
    "config_from_json",
    "config_to_json",
    "DataBus",
    "DataExtended",
    "DeviceCapabilities",
    "DisplayConfig",
    "FirmwareVersion",
    "firmware_ota_asset",
    "firmware_release_repo",
    "FitMode",
    "FlashConfig",
    "FlashIcType",
    "GlobalConfig",
    "ICType",
    "LedConfig",
    "LedFlashConfig",
    "LedFlashStep",
    "ManufacturerData",
    "NfcConfig",
    "NfcFieldDetectMode",
    "NfcIcType",
    "NfcRecordType",
    "OpenDisplayBoardType",
    "PassiveBuzzer",
    "PowerMode",
    "PowerOption",
    "RefreshMode",
    "Rotation",
    "SecurityConfig",
    "SeeedBoardType",
    "SensorData",
    "SolumBoardType",
    "SystemConfig",
    "TouchController",
    "TouchIcType",
    "WifiConfig",
    "WaveshareBoardType",
    "get_board_type_name",
    "get_manufacturer_name",
]
